server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none #
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect #
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 132132132
