server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.204.239.206:3306/user_management
    username: luong
    password: 1
  jpa:
    hibernate:
      ddl-auto: none #
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        dialect: org.hibernate.dialect.MySQL5Dialect #
        connection:
          username: luong
          password: 1
          url: jdbc:mysql://52.204.239.206:3306/user_management
          driver_class: com.mysql.cj.jdbc.Driver
        order_updates: true
    show-sql: true
    generate-ddl: true
